### ISSUE TITLE
bundle unable to present as a scalar 

### ISSUE THREAD

**Issue by kyocum** [kyocum/disdat#118]
Task return <str>, but when we try to present the bundle as a scalar, it is packed in an array, and we get the following error:

Traceback (most recent call last):
  File "/Users/bkang1/.virtualenvs/cstream/bin/dsdt", line 10, in <module>
    sys.exit(main())
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/dsdt.py", line 132, in main
    args.func(args)
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/fs.py", line 1884, in <lambda>
    cat_p.set_defaults(func=lambda args: _cat(fs, args))
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/fs.py", line 1781, in _cat
    result = fs.cat(args.bundle, uuid=args.uuid, tags=common.parse_args_tags(args.tag), file=args.file)
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/fs.py", line 748, in cat
    other = data_context.present_hfr(hfr)
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/data_context.py", line 1345, in present_hfr
    return self.convert_hfr2scalar(hfr)
  File "/Users/bkang1/.virtualenvs/cstream/lib/python3.6/site-packages/disdat/data_context.py", line 1268, in convert_hfr2scalar
    return nda.item()
ValueError: can only convert an array of size 1 to a Python scalar

**Comment by kyocum** [comment]
Resolved.
