### ISSUE TITLE
db table link fails on pull 

### ISSUE THREAD

**Issue by kyocum** [kyocum/disdat#38]
2018-10-10 20:09:28,680 - disdat.data_context - ERROR - Unable to use a string-based database reference[db://Analytics.DATA_SCIENCE.DISDAT_careops3_tto_daily_forecast_blend_77e7ddf1fac24617984f19eac1ce0338@pprddaavth-vip.ie.intuit.net], please return DBTarget object instead.
Traceback (most recent call last):
  File "/Users/crivera5/.virtualenvs/careops/bin/dsdt", line 11, in <module>
    sys.exit(main())
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/dsdt.py", line 122, in main
    args.func(args)
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/fs.py", line 1727, in <lambda>
    pull_p.set_defaults(func=lambda args: _pull(fs, args))
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/fs.py", line 1565, in _pull
    fs.pull(bundle, uuid, localize=args.localize)
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/fs.py", line 1474, in pull
    s3_uuid, data_context)
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/fs.py", line 1312, in _localize_hfr
    DataContext.copy_in_files(f, managed_path)
  File "/Users/crivera5/.virtualenvs/careops/lib/python2.7/site-packages/disdat/data_context.py", line 1116, in copy_in_files
    raise Exception("data_context:copy_in_files error trying to copy in string-based database reference.")
Exception: data_context:copy_in_files error trying to copy in string-based database reference.

**Comment by kyocum** [comment]
Resolved via warning and ignoring the link (continuing to next item in bundle).
